sources:
  - name: raw_bronze
    description: "Raw data from the Olist e-commerce dataset, loaded as external tables on S3."
    database: OLIST_LAKEHOUSE
    schema: RAW_BRONZE
    config:
      loaded_at_field: metadata$file_last_modified
      freshness:
        warn_after: {count: 24, period: hour}
        error_after: {count: 48, period: hour}
    tables:
      - name: olist_customers_dataset
        columns:
          - name: value
            data_type: variant
          - name: customer_id
            data_type: varchar
            description: Unique identifier for each customer in the dataset.
          - name: customer_unique_id
            data_type: varchar
            description: Unique identifier for each customer across all orders, allowing for tracking of repeat customers.
          - name: customer_zip_code_prefix
            data_type: varchar
          - name: customer_city
            data_type: varchar
          - name: customer_state
            data_type: varchar

      - name: olist_geolocation_dataset
        columns:
          - name: value
            data_type: variant
          - name: geolocation_zip_code_prefix
            data_type: varchar
          - name: geolocation_lat
            data_type: number
          - name: geolocation_lng
            data_type: number
          - name: geolocation_city
            data_type: varchar
          - name: geolocation_state
            data_type: varchar

      - name: olist_order_items_dataset
        columns:
          - name: value
            data_type: variant
          - name: order_id
            data_type: varchar
          - name: order_item_id
            data_type: number
          - name: product_id
            data_type: varchar
          - name: seller_id
            data_type: varchar
          - name: shipping_limit_date
            data_type: timestamp_ntz
          - name: price
            data_type: number
          - name: freight_value
            data_type: number

      - name: olist_order_payments_dataset
        columns:
          - name: value
            data_type: variant
          - name: order_id
            data_type: varchar
          - name: payment_sequential
            data_type: number
          - name: payment_type
            data_type: varchar
          - name: payment_installments
            data_type: number
          - name: payment_value
            data_type: number

      - name: olist_order_reviews_dataset
        columns:
          - name: value
            data_type: variant
          - name: review_id
            data_type: varchar
          - name: order_id
            data_type: varchar
          - name: review_score
            data_type: number
          - name: review_comment_title
            data_type: varchar
          - name: review_comment_message
            data_type: varchar
          - name: review_creation_date
            data_type: timestamp_ntz
          - name: review_answer_timestamp
            data_type: timestamp_ntz

      - name: olist_orders_dataset
        columns:
          - name: value
            data_type: variant
          - name: order_id
            data_type: varchar
          - name: customer_id
            data_type: varchar
          - name: order_status
            data_type: varchar
          - name: order_purchase_timestamp
            data_type: timestamp_ntz
          - name: order_approved_at
            data_type: timestamp_ntz
          - name: order_delivered_carrier_date
            data_type: timestamp_ntz
          - name: order_delivered_customer_date
            data_type: timestamp_ntz
          - name: order_estimated_delivery_date
            data_type: timestamp_ntz

      - name: olist_products_dataset
        columns:
          - name: value
            data_type: variant
          - name: product_id
            data_type: varchar
          - name: product_category_name
            data_type: varchar
          - name: product_name_lenght
            data_type: number
          - name: product_description_lenght
            data_type: number
          - name: product_photos_qty
            data_type: number
          - name: product_weight_g
            data_type: number
          - name: product_length_cm
            data_type: number
          - name: product_height_cm
            data_type: number
          - name: product_width_cm
            data_type: number

      - name: olist_sellers_dataset
        columns:
          - name: value
            data_type: variant
          - name: seller_id
            data_type: varchar
          - name: seller_zip_code_prefix
            data_type: varchar
          - name: seller_city
            data_type: varchar
          - name: seller_state
            data_type: varchar

      - name: product_category_name_translation
        columns:
          - name: value
            data_type: variant
          - name: product_category_name
            data_type: varchar
          - name: product_category_name_english
            data_type: varchar
