WITH

SOURCE AS (

    SELECT * FROM {{ source('raw_bronze', 'olist_sellers_dataset') }}

),

RENAMED AS (

    SELECT
        SELLER_ID::VARCHAR AS SELLER_ID,
        SELLER_ZIP_CODE_PREFIX::VARCHAR AS SELLER_ZIP_CODE_PREFIX,
        SELLER_CITY::VARCHAR AS SELLER_CITY,
        SELLER_STATE::VARCHAR AS SELLER_STATE

    FROM SOURCE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY SELLER_ID
        ORDER BY SELLER_ID
    ) = 1

)

SELECT * FROM RENAMED
