WITH SOURCE AS (

    SELECT * FROM {{ source('raw_bronze', 'olist_orders_dataset') }}

),

RENAMED AS (

    SELECT
        ORDER_ID::VARCHAR AS ORDER_ID,
        CUSTOMER_ID::VARCHAR AS CUSTOMER_ID,
        ORDER_STATUS::VARCHAR AS ORDER_STATUS,
        ORDER_PURCHASE_TIMESTAMP::TIMESTAMP_NTZ AS ORDER_PURCHASE_TIMESTAMP,
        ORDER_APPROVED_AT::TIMESTAMP_NTZ AS ORDER_APPROVED_AT,
        ORDER_DELIVERED_CARRIER_DATE::TIMESTAMP_NTZ AS ORDER_DELIVERED_CARRIER_DATE,
        ORDER_DELIVERED_CUSTOMER_DATE::TIMESTAMP_NTZ AS ORDER_DELIVERED_CUSTOMER_DATE,
        ORDER_ESTIMATED_DELIVERY_DATE::TIMESTAMP_NTZ AS ORDER_ESTIMATED_DELIVERY_DATE

    FROM SOURCE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ORDER_ID
        ORDER BY ORDER_PURCHASE_TIMESTAMP DESC
    ) = 1

)

SELECT * FROM RENAMED
