WITH

SOURCE AS (

    SELECT * FROM {{ source('raw_bronze', 'olist_order_items_dataset') }}

),

RENAMED AS (

    SELECT
        ORDER_ID::VARCHAR AS ORDER_ID,
        ORDER_ITEM_ID::NUMBER AS ORDER_ITEM_ID,
        PRODUCT_ID::VARCHAR AS PRODUCT_ID,
        SELLER_ID::VARCHAR AS SELLER_ID,
        SHIPPING_LIMIT_DATE::TIMESTAMP_NTZ AS SHIPPING_LIMIT_DATE,
        PRICE::NUMBER(10, 2) AS PRICE,
        FREIGHT_VALUE::NUMBER(10, 2) AS FREIGHT_VALUE

    FROM SOURCE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ORDER_ID, ORDER_ITEM_ID
        ORDER BY SHIPPING_LIMIT_DATE DESC
    ) = 1

)

SELECT * FROM RENAMED
