WITH

SOURCE AS (

    SELECT * FROM {{ source('raw_bronze', 'olist_customers_dataset') }}

),

RENAMED AS (

    SELECT
        CUSTOMER_ID::VARCHAR AS CUSTOMER_ID,
        CUSTOMER_UNIQUE_ID::VARCHAR AS CUSTOMER_UNIQUE_ID,
        CUSTOMER_ZIP_CODE_PREFIX::VARCHAR AS CUSTOMER_ZIP_CODE_PREFIX,
        CUSTOMER_CITY::VARCHAR AS CUSTOMER_CITY,
        CUSTOMER_STATE::VARCHAR AS CUSTOMER_STATE

    FROM SOURCE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CUSTOMER_ID
        ORDER BY CUSTOMER_ID
    ) = 1

)

SELECT * FROM RENAMED
