WITH

SOURCE AS (

    SELECT * FROM {{ source('raw_bronze', 'olist_geolocation_dataset') }}

),

RENAMED AS (

    SELECT
        GEOLOCATION_ZIP_CODE_PREFIX::VARCHAR AS GEOLOCATION_ZIP_CODE_PREFIX,
        GEOLOCATION_LAT::NUMBER(10, 8) AS GEOLOCATION_LAT,
        GEOLOCATION_LNG::NUMBER(11, 8) AS GEOLOCATION_LNG,
        GEOLOCATION_CITY::VARCHAR AS GEOLOCATION_CITY,
        GEOLOCATION_STATE::VARCHAR AS GEOLOCATION_STATE

    FROM SOURCE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY GEOLOCATION_ZIP_CODE_PREFIX, GEOLOCATION_LAT, GEOLOCATION_LNG
        ORDER BY GEOLOCATION_ZIP_CODE_PREFIX
    ) = 1

)

SELECT * FROM RENAMED
