WITH

SOURCE AS (

    SELECT * FROM {{ source('raw_bronze', 'olist_order_payments_dataset') }}

),

RENAMED AS (

    SELECT
        ORDER_ID::VARCHAR AS ORDER_ID,
        PAYMENT_SEQUENTIAL::NUMBER AS PAYMENT_SEQUENTIAL,
        PAYMENT_TYPE::VARCHAR AS PAYMENT_TYPE,
        PAYMENT_INSTALLMENTS::NUMBER AS PAYMENT_INSTALLMENTS,
        PAYMENT_VALUE::NUMBER(10, 2) AS PAYMENT_VALUE

    FROM SOURCE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ORDER_ID, PAYMENT_SEQUENTIAL
        ORDER BY ORDER_ID
    ) = 1

)

SELECT * FROM RENAMED
