WITH

SOURCE AS (

    SELECT * FROM {{ source('raw_bronze', 'olist_order_reviews_dataset') }}

),

RENAMED AS (

    SELECT
        REVIEW_ID::VARCHAR AS REVIEW_ID,
        ORDER_ID::VARCHAR AS ORDER_ID,
        REVIEW_SCORE::NUMBER AS REVIEW_SCORE,
        REVIEW_COMMENT_TITLE::VARCHAR AS REVIEW_COMMENT_TITLE,
        REVIEW_COMMENT_MESSAGE::VARCHAR AS REVIEW_COMMENT_MESSAGE,
        REVIEW_CREATION_DATE::TIMESTAMP_NTZ AS REVIEW_CREATION_DATE,
        REVIEW_ANSWER_TIMESTAMP::TIMESTAMP_NTZ AS REVIEW_ANSWER_TIMESTAMP

    FROM SOURCE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY REVIEW_ID
        ORDER BY REVIEW_CREATION_DATE DESC
    ) = 1

)

SELECT * FROM RENAMED
