WITH

SOURCE AS (

    SELECT * FROM {{ source('raw_bronze', 'olist_products_dataset') }}

),

RENAMED AS (

    SELECT
        PRODUCT_ID::VARCHAR AS PRODUCT_ID,
        PRODUCT_CATEGORY_NAME::VARCHAR AS PRODUCT_CATEGORY_NAME,
        PRODUCT_NAME_LENGHT::NUMBER AS PRODUCT_NAME_LENGTH,
        PRODUCT_DESCRIPTION_LENGHT::NUMBER AS PRODUCT_DESCRIPTION_LENGTH,
        PRODUCT_PHOTOS_QTY::NUMBER AS PRODUCT_PHOTOS_QTY,
        PRODUCT_WEIGHT_G::NUMBER AS PRODUCT_WEIGHT_G,
        PRODUCT_LENGTH_CM::NUMBER AS PRODUCT_LENGTH_CM,
        PRODUCT_HEIGHT_CM::NUMBER AS PRODUCT_HEIGHT_CM,
        PRODUCT_WIDTH_CM::NUMBER AS PRODUCT_WIDTH_CM

    FROM SOURCE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY PRODUCT_ID
        ORDER BY PRODUCT_ID
    ) = 1

)

SELECT * FROM RENAMED
