WITH PRODUCTS AS (
    SELECT * FROM {{ ref('stg_olist_products') }}
),

TRANSLATIONS AS (
    SELECT * FROM {{ ref('stg_product_category_name_translation') }}
),

ORDER_ITEMS AS (
    SELECT * FROM {{ ref('stg_olist_order_items') }}
),

ORDER_REVIEWS AS (
    SELECT * FROM {{ ref('stg_olist_order_reviews') }}
),

PRODUCT_SALES AS (
    SELECT
        PRODUCT_ID,
        COUNT(ORDER_ITEM_ID) AS TOTAL_UNITS_SOLD,
        SUM(PRICE) AS TOTAL_REVENUE_GENERATED
    FROM ORDER_ITEMS
    GROUP BY 1
),

PRODUCT_REVIEWS AS (
    SELECT
        OI.PRODUCT_ID,
        ROUND(AVG(R.REVIEW_SCORE), 2) AS AVERAGE_REVIEW_SCORE,
        COUNT(DISTINCT R.REVIEW_ID) AS TOTAL_REVIEWS
    FROM ORDER_ITEMS AS OI
    INNER JOIN ORDER_REVIEWS AS R ON OI.ORDER_ID = R.ORDER_ID
    GROUP BY 1
)

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME,
    T.PRODUCT_CATEGORY_NAME_ENGLISH,
    P.PRODUCT_NAME_LENGTH,
    P.PRODUCT_DESCRIPTION_LENGTH,
    P.PRODUCT_PHOTOS_QTY,
    P.PRODUCT_WEIGHT_G,
    P.PRODUCT_LENGTH_CM,
    P.PRODUCT_HEIGHT_CM,
    P.PRODUCT_WIDTH_CM,
    R.AVERAGE_REVIEW_SCORE,
    COALESCE(S.TOTAL_UNITS_SOLD, 0) AS TOTAL_UNITS_SOLD,
    COALESCE(S.TOTAL_REVENUE_GENERATED, 0.00) AS TOTAL_REVENUE_GENERATED,
    COALESCE(R.TOTAL_REVIEWS, 0) AS TOTAL_REVIEWS
FROM PRODUCTS AS P
LEFT JOIN TRANSLATIONS AS T ON P.PRODUCT_CATEGORY_NAME = T.PRODUCT_CATEGORY_NAME
LEFT JOIN PRODUCT_SALES AS S ON P.PRODUCT_ID = S.PRODUCT_ID
LEFT JOIN PRODUCT_REVIEWS AS R ON P.PRODUCT_ID = R.PRODUCT_ID
