WITH SELLERS AS (
    SELECT * FROM {{ ref('stg_olist_sellers') }}
),

ORDER_ITEMS AS (
    SELECT * FROM {{ ref('stg_olist_order_items') }}
),

ORDERS AS (
    SELECT * FROM {{ ref('stg_olist_orders') }}
),

SELLER_PERFORMANCE AS (
    SELECT
        OI.SELLER_ID,
        SUM(OI.PRICE) AS TOTAL_SALES_VALUE,
        COUNT(DISTINCT OI.ORDER_ID) AS TOTAL_ORDERS_FULFILLED,
        ROUND(AVG(OI.FREIGHT_VALUE), 2) AS AVERAGE_FREIGHT_VALUE,
        ROUND(AVG(DATEDIFF('day', O.ORDER_PURCHASE_TIMESTAMP, O.ORDER_DELIVERED_CARRIER_DATE)), 2)
            AS AVERAGE_FULFILLMENT_DAYS
    FROM ORDER_ITEMS AS OI
    INNER JOIN ORDERS AS O ON OI.ORDER_ID = O.ORDER_ID
    GROUP BY 1
)

SELECT
    S.SELLER_ID,
    S.SELLER_ZIP_CODE_PREFIX,
    S.SELLER_CITY,
    S.SELLER_STATE,
    SP.AVERAGE_FULFILLMENT_DAYS,
    COALESCE(SP.TOTAL_SALES_VALUE, 0.00) AS TOTAL_SALES_VALUE,
    COALESCE(SP.TOTAL_ORDERS_FULFILLED, 0) AS TOTAL_ORDERS_FULFILLED,
    COALESCE(SP.AVERAGE_FREIGHT_VALUE, 0.00) AS AVERAGE_FREIGHT_VALUE
FROM SELLERS AS S
LEFT JOIN SELLER_PERFORMANCE AS SP ON S.SELLER_ID = SP.SELLER_ID
