WITH ORDER_ITEMS AS (
    SELECT * FROM {{ ref('stg_olist_order_items') }}
),

ORDERS AS (
    SELECT * FROM {{ ref('stg_olist_orders') }}
)

SELECT
    OI.ORDER_ID,
    OI.ORDER_ITEM_ID,
    O.CUSTOMER_ID,
    OI.PRODUCT_ID,
    OI.SELLER_ID,
    OI.SHIPPING_LIMIT_DATE,
    OI.PRICE,
    OI.FREIGHT_VALUE,
    O.ORDER_STATUS,
    O.ORDER_PURCHASE_TIMESTAMP
FROM ORDER_ITEMS AS OI
INNER JOIN ORDERS AS O ON OI.ORDER_ID = O.ORDER_ID
