WITH REVIEWS AS (
    SELECT * FROM {{ ref('stg_olist_order_reviews') }}
),

ORDERS AS (
    SELECT * FROM {{ ref('stg_olist_orders') }}
)

SELECT
    R.REVIEW_ID,
    R.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_STATUS,
    R.REVIEW_SCORE,
    R.REVIEW_COMMENT_TITLE,
    R.REVIEW_COMMENT_MESSAGE,
    R.REVIEW_CREATION_DATE,
    R.REVIEW_ANSWER_TIMESTAMP
FROM REVIEWS AS R
LEFT JOIN ORDERS AS O ON R.ORDER_ID = O.ORDER_ID
