CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND= 10
AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS OLIST_LAKEHOUSE;

CREATE SCHEMA IF NOT EXISTS OLIST_LAKEHOUSE.RAW_BRONZE;
CREATE SCHEMA IF NOT EXISTS OLIST_LAKEHOUSE.ANALYTICS_GOLD;

