GRANT MODIFY PROGRAMMATIC AUTHENTICATION METHODS ON USER cashalot1 TO ROLE ALL_USERS_ROLE;
ALTER USER cashalot1 SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoi+k4vrPCUYwpMT+Jc1z2suOLmVfxunHBsm7FMHD4m2yZXjPs/cNofhjiW/n9NV17n3f6CzPYC7e0d1aBKdherPYdT/xRp1Gq26BEUvU/a4WcJU3R173WWudRgixr94OmzzMdgmHtKNgeCkyh2QvGfVeBBNivl5eQw0sLI6ciSgCmgHGuEuBY/dml0iKp8im1JnGJd8WE37/H5CJ4YJaUpjGDWFXlR3cLZJ0e8bEXR+g49iOSaSWbUGyAvKHyxFnTsv0e86cI7VmafsYGYUpgdSUt5uPkoU8rAgh003YMwXYh/S9ygWbo6iD/MA+6l1Z7QopleGixXHhf1I9vGhDwwIDAQAB';

GRANT ROLE ALL_USERS_ROLE TO USER cashalot1;

CREATE ROLE OLIST_ROLE;
GRANT USAGE ON DATABASE OLIST_LAKEHOUSE TO ROLE OLIST_ROLE;
GRANT CREATE SCHEMA ON DATABASE OLIST_LAKEHOUSE TO ROLE OLIST_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE OLIST_LAKEHOUSE TO ROLE OLIST_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE ON FUTURE SCHEMAS IN DATABASE OLIST_LAKEHOUSE TO ROLE OLIST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OLIST_LAKEHOUSE TO ROLE OLIST_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE ON ALL SCHEMAS IN DATABASE OLIST_LAKEHOUSE TO ROLE OLIST_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE OLIST_LAKEHOUSE TO ROLE OLIST_ROLE;
GRANT ROLE OLIST_ROLE TO USER cashalot1;
GRANT MODIFY PROGRAMMATIC AUTHENTICATION METHODS ON USER cashalot1 TO ROLE OLIST_ROLE;

CREATE DATABASE OLIST_LAKEHOUSE_PROD;

GRANT USAGE ON DATABASE OLIST_LAKEHOUSE_PROD TO ROLE OLIST_ROLE;
GRANT CREATE SCHEMA ON DATABASE OLIST_LAKEHOUSE_PROD TO ROLE OLIST_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE OLIST_LAKEHOUSE_PROD TO ROLE OLIST_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE ON FUTURE SCHEMAS IN DATABASE OLIST_LAKEHOUSE_PROD TO ROLE OLIST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OLIST_LAKEHOUSE_PROD TO ROLE OLIST_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE ON ALL SCHEMAS IN DATABASE OLIST_LAKEHOUSE_PROD TO ROLE OLIST_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE OLIST_LAKEHOUSE_PROD TO ROLE OLIST_ROLE;
